# render.yaml
# This file tells Render how to deploy your project.
# It defines two services: a static site for the frontend and a web service for the backend.

services:
  # 1. The Static Frontend Service
  - type: static
    name: ai-video-frontend
    env: static # Specifies this is a static site
    rootDir: frontend # The folder containing the frontend files
    buildFilter:
      paths:
      - frontend/** # Only rebuild this service if files in the frontend folder change
    routes:
      - type: rewrite
        source: / # All requests go to the main index.html
        destination: /index.html

  # 2. The Python Backend Service
  - type: web
    name: ai-video-backend
    env: python # Specifies this is a Python service
    rootDir: backend # The folder containing the backend files
    plan: free # Use Render's free tier
    buildFilter:
      paths:
      - backend/** # Only rebuild this service if files in the backend folder change
    buildCommand: "chmod +x start.sh" # Make the startup script executable
    startCommand: "./start.sh" # Run the startup script
    healthCheckPath: "/" # Render will check this path to see if the service is alive
    disks:
      - name: huggingface-cache
        mountPath: /var/data/huggingface_cache # Mount the persistent disk
        sizeGB: 5 # Allocate 5 GB of persistent storage for our model
